apiVersion: v1
kind: Service
metadata:
  labels:
    service: postgis-client
  name: postgis-client
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  - name: "22"
    port: 22
    targetPort: 22
  selector:
    service: postgis-client
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: postgis-client-2
  name: postgis-client-2
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  - name: "22"
    port: 22
    targetPort: 22
  selector:
    service: postgis-client-2
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: postgis-client-12-13
  name: postgis-client-12-13
spec:
  ports:
  - name: 5432
    port: 5432
    targetPort: 5432
  - name: 22
    port: 22
    targetPort: 22
  selector:
    service: postgis-client-12-13
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: postgis-client-12-13
  name: postgis-client-12-13
spec:
  ports:
  - name: 5432
    port: 5432
    targetPort: 5432
  - name: 22
    port: 22
    targetPort: 22
  selector:
    service: postgis-client-12-13
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: postgis-client-12-13
  name: postgis-client-12-13
spec:
  ports:
  - name: 5432
    port: 5432
    targetPort: 5432
  - name: 22
    port: 22
    targetPort: 22
  selector:
    service: postgis-client-12-13
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: postgis-client-12-13
  name: postgis-client-12-13
spec:
  ports:
  - name: 5432
    port: 5432
    targetPort: 5432
  - name: 22
    port: 22
    targetPort: 22
  selector:
    service: postgis-client-12-13
status:
  loadBalancer: {}
