apiVersion: v1
kind: Service
metadata:
  labels:
    service: postgis-client-12-12
  name: postgis-client-12-12
spec:
  ports:
  - name: p5432
    port: 5432
    targetPort: 5432
  - name: p22
    port: 22
    targetPort: 22
  selector:
    service: postgis-client-12-12
status:
  loadBalancer: {}
