apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: postgis-client
  name: postgis-client
spec:
  serviceName: postgis-client
  replicas: 1
  selector:
    matchLabels:
      service: postgis-client
  template:
    metadata:
      labels:
        service: postgis-client
    spec:
      containers:
      - image: postgis/postgis:15-master
        name: postgis-client
        envFrom:
        - configMapRef:
            name: postgis-configmap
        env:
        - name: POSTGRES_PASSWORD
          value: GO6h5AC2zQP8Pq1
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: 7Gi
            cpu: 1.5
          requests:
            memory: 1Gi
            cpu: 100m
        volumeMounts:
        - mountPath: /var/lib/postgresql/12/main
          name: azure-managed-disk
      tolerations:
      - key: layer
        operator: Equal
        value: postgre
        effect: NoSchedule
      nodeSelector:
        layer: postgre
  volumeClaimTemplates:
  - metadata:
      name: azure-managed-disk
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: default
      resources:
        requests:
          storage: 64Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: postgis-client-2
  name: postgis-client-2
spec:
  serviceName: postgis-client-2
  replicas: 1
  selector:
    matchLabels:
      service: postgis-client-2
  template:
    metadata:
      labels:
        service: postgis-client-2
    spec:
      containers:
      - image: windgiswesteuropecr001.azurecr.io/postgis:latest
        name: postgis-client-2
        envFrom:
        - configMapRef:
            name: postgis-configmap
        env:
        - name: POSTGRES_PASSWORD
          value: -NdQ2+6L?kpzr5Sy
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: 7Gi
            cpu: 1.5
          requests:
            memory: 1Gi
            cpu: 100m
        volumeMounts:
        - mountPath: /var/lib/postgresql/12/main
          name: azure-managed-disk
      tolerations:
      - key: layer
        operator: Equal
        value: postgre
        effect: NoSchedule
      nodeSelector:
        layer: postgre
  volumeClaimTemplates:
  - metadata:
      name: azure-managed-disk
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: default
      resources:
        requests:
          storage: 64Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: postgis-client-12-13
  name: postgis-client-12-13
spec:
  serviceName: postgis-client-12-13
  replicas: 1
  selector:
    matchLabels:
      service: postgis-client-12-13
  template:
    metadata:
      labels:
        service: postgis-client-12-13
    spec:
      containers:
      - image: postgis/postgis:15-master
        name: postgis-client-12-13
        envFrom:
        - configMapRef:
            name: postgis-configmap
        env:
        - name: POSTGRES_PASSWORD
          value: string
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: 7Gi
            cpu: 1.5
          requests:
            memory: 1Gi
            cpu: 100m
        volumeMounts:
        - mountPath: /var/lib/postgresql/12/main
          name: azure-managed-disk
      tolerations:
      - key: layer
        operator: Equal
        value: postgre
        effect: NoSchedule
      nodeSelector:
        layer: postgre
  volumeClaimTemplates:
  - metadata:
      name: azure-managed-disk
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: default
      resources:
        requests:
          storage: 64Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: postgis-client-21-21
  name: postgis-client-21-21
spec:
  serviceName: postgis-client-21-21
  replicas: 1
  selector:
    matchLabels:
      service: postgis-client-21-21
  template:
    metadata:
      labels:
        service: postgis-client-21-21
    spec:
      containers:
      - image: postgis/postgis:15-master
        name: postgis-client-21-21
        envFrom:
        - configMapRef:
            name: postgis-configmap
        env:
        - name: POSTGRES_PASSWORD
          value: string
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: 7Gi
            cpu: 1.5
          requests:
            memory: 1Gi
            cpu: 100m
        volumeMounts:
        - mountPath: /var/lib/postgresql/12/main
          name: azure-managed-disk
      tolerations:
      - key: layer
        operator: Equal
        value: postgre
        effect: NoSchedule
      nodeSelector:
        layer: postgre
  volumeClaimTemplates:
  - metadata:
      name: azure-managed-disk
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: default
      resources:
        requests:
          storage: 64Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: postgis-client-30-30
  name: postgis-client-30-30
spec:
  serviceName: postgis-client-30-30
  replicas: 1
  selector:
    matchLabels:
      service: postgis-client-30-30
  template:
    metadata:
      labels:
        service: postgis-client-30-30
    spec:
      containers:
      - image: postgis/postgis:15-master
        name: postgis-client-30-30
        envFrom:
        - configMapRef:
            name: postgis-configmap
        env:
        - name: POSTGRES_PASSWORD
          value: someotherpassword
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: 7Gi
            cpu: 1.5
          requests:
            memory: 1Gi
            cpu: 100m
        volumeMounts:
        - mountPath: /var/lib/postgresql/12/main
          name: azure-managed-disk
      tolerations:
      - key: layer
        operator: Equal
        value: postgre
        effect: NoSchedule
      nodeSelector:
        layer: postgre
  volumeClaimTemplates:
  - metadata:
      name: azure-managed-disk
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: default
      resources:
        requests:
          storage: 64Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: postgis-client-50-50
  name: postgis-client-50-50
spec:
  serviceName: postgis-client-50-50
  replicas: 1
  selector:
    matchLabels:
      service: postgis-client-50-50
  template:
    metadata:
      labels:
        service: postgis-client-50-50
    spec:
      containers:
      - image: postgis/postgis:15-master
        name: postgis-client-50-50
        envFrom:
        - configMapRef:
            name: postgis-configmap
        env:
        - name: POSTGRES_PASSWORD
          value: smecherie
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: 7Gi
            cpu: 1.5
          requests:
            memory: 1Gi
            cpu: 100m
        volumeMounts:
        - mountPath: /var/lib/postgresql/12/main
          name: azure-managed-disk
      tolerations:
      - key: layer
        operator: Equal
        value: postgre
        effect: NoSchedule
      nodeSelector:
        layer: postgre
  volumeClaimTemplates:
  - metadata:
      name: azure-managed-disk
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: default
      resources:
        requests:
          storage: 64Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: postgis-client-67-772
  name: postgis-client-67-772
spec:
  serviceName: postgis-client-67-772
  replicas: 1
  selector:
    matchLabels:
      service: postgis-client-67-772
  template:
    metadata:
      labels:
        service: postgis-client-67-772
    spec:
      containers:
      - image: postgis/postgis:15-master
        name: postgis-client-67-772
        envFrom:
        - configMapRef:
            name: postgis-configmap
        env:
        - name: POSTGRES_PASSWORD
          value: string
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: 7Gi
            cpu: 1.5
          requests:
            memory: 1Gi
            cpu: 100m
        volumeMounts:
        - mountPath: /var/lib/postgresql/12/main
          name: azure-managed-disk
      tolerations:
      - key: layer
        operator: Equal
        value: postgre
        effect: NoSchedule
      nodeSelector:
        layer: postgre
  volumeClaimTemplates:
  - metadata:
      name: azure-managed-disk
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: default
      resources:
        requests:
          storage: 64Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: postgis-client-123-123
  name: postgis-client-123-123
spec:
  serviceName: postgis-client-123-123
  replicas: 1
  selector:
    matchLabels:
      service: postgis-client-121-121
  template:
    metadata:
      labels:
        service: postgis-client-121-121
    spec:
      containers:
      - image: postgis/postgis:15-master
        name: postgis-client-121-121
        envFrom:
        - configMapRef:
            name: postgis-configmap
        env:
        - name: POSTGRES_USER
          value: atlasadmin
        - name: POSTGRES_PASSWORD
          value: '{password}'
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: 7Gi
            cpu: 1.5
          requests:
            memory: 1Gi
            cpu: 100m
        volumeMounts:
        - mountPath: /var/lib/postgresql/12/main
          name: azure-managed-disk
      tolerations:
      - key: layer
        operator: Equal
        value: postgre
        effect: NoSchedule
      nodeSelector:
        layer: postgre
  volumeClaimTemplates:
  - metadata:
      name: azure-managed-disk
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: default
      resources:
        requests:
          storage: 64Gi
