apiVersion: batch/v1
kind: CronJob
metadata:
  name: "postgis-backup-cronjob-1-2"
spec:
  schedule: "5 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: pgsql-backup
            image: windgiswesteuropecr001.azurecr.io/postgres-backup:1.6
            imagePullPolicy: Always
            resources:
              requests:
                memory: "32Mi"
                cpu: "100m"
              limits:
                memory: "128Mi"
                cpu: "500m"
            env:
            - name: PGHOST
              value: "postgis-client-1-2"
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGUSER
              value: atlasadmin
            - name: PGPASSWORD
              value: "09?rg1xKxDTC"
            - name: EMAILRECIPIENT
              value: Lautec.GIS.Monitor@rebeldot.com
            - name: EMAILSENDER
              value: windgisbackup@lautec.com
            - name: CUSTOMER
              value: "postgis-client-1-2"
            volumeMounts:
            - mountPath: "/pg_backup"
              name: backup-volume
            - mountPath: /data
              name: redis-pvc              
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: postgis-backup-pvc
            - name: redis-pvc
              persistentVolumeClaim:
                claimName: redis-pvc
